### ISSUE TITLE
Getting started?

### ISSUE THREAD

**Issue by JoeMurray** [coopsymbiotic/coop.symbiotic.sparkpostrouter#1]
Just noticed this extension and like the purpose. Would it be possible to put into Readme how to configure the Settings, or is it obvious?

**Comment by mlutfy** [comment]
I think it is pretty obvious, but might be worth glancing over the code?

Except: because there is only an API call, not a `Job`, it's not connected to CiviCRM's scheduled-jobs by default. You can either add an entry manually, or add a cron job on your host.

I use:

```
/10 * * * * /usr/bin/env php /usr/local/bin/drush -u 1 @crm.symbiotic.coop cvapi Sparkpostrouter.process_messages
```

where `crm.symbiotic.coop` is our central CRM where we have contact records for all our clients, and where we store the webhook URL of the client (the extension does not hardcode the webhook, because it depends on whether the site is bilingual, Drupal7/8/WP/J, etc).

We also usually run the cron every 15 mins, but this job should run more often. I find that 10 mins is a good default.

**Comment by JoeMurray** [comment]
Submitted PR with more extension installation instructions.
